spring:
  application:
    name: mc_loyalty
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/loyalty}
    username: postgres
    password: bnm11091
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  liquibase:
    change-log: classpath:db/changelog/2025/03/26-01-changelog.xml
    enabled: true
server:
  port: 8081